# Copyright (C) Daniel Stenberg, <daniel@haxx.se>, et al.
#
# SPDX-License-Identifier: curl

name: Markdown links

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master
  #     - '*/ci'
  #   paths:
  #     - '.github/workflows/linkcheck.yml'
  #     - '**.md'
  # pull_request:
  #   branches:
  #     - master
  #   paths:
  #     - '.github/workflows/linkcheck.yml'
  #     - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: {}

jobs:
  # Docs: https://github.com/marketplace/actions/markdown-link-check
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Eco-CI Init
        uses: green-coding-berlin/eco-ci-energy-estimation@v2
        with:
          task: start-measurement

      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'

      - name: Eco-CI Measurement
        uses: green-coding-berlin/eco-ci-energy-estimation@v2
        with:
          task: get-measurement
          label: 'linkcheck'

      - name: Eco-CI Results
        uses: green-coding-berlin/eco-ci-energy-estimation@v2
        with:
          task: display-results
